import { SWRProvider } from "@/components/custom/shared/SWRProvider";
import { Provider } from "@/components/ui/provider";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { geistMono, geistSans } from "./fonts";

export const metadata: Metadata = {
  title: "tradaz-business",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider>
          <SWRProvider>
            {children}
            <Toaster />
          </SWRProvider>
        </Provider>
      </body>
    </html>
  );
}
