import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Provider } from "../components/ui/provider";
import NavBar from "./NavBar";
import { SideBar } from "./SideBar";
import { Box } from "@chakra-ui/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "tradaz-business",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        suppressHydrationWarning
      >
        <Provider>
          <NavBar />
          <SideBar />

          <Box as="main" pt="60px" pl={{ base: "0", md: "250px" }} minH="100vh">
            <Box p={{ base: 4, md: 8 }}>{children}</Box>
          </Box>
        </Provider>
      </body>
    </html>
  );
}
